In [1]:
from OpenCell.Materials.RawMaterials import CurrentCollectorMaterial
from OpenCell.Materials.CurrentCollectors import TablessCurrentCollector
from OpenCell import __version__

import pandas as pd
from datetime import datetime as dt

In [2]:

cathode_current_collector_material = CurrentCollectorMaterial.from_database('Aluminum')

cathode_current_collector = TablessCurrentCollector(
    material=cathode_current_collector_material,
    width=151,
    length=2975,
    coated_width=142,
    insulation_width=3,
    thickness=13,
    name='QNAS-S40160NL'
)

In [3]:
cathode_current_collector._get_full_top_down_view()

In [ ]:
# Cathode formulation

In [ ]:

from OpenCell.Materials.ElectrodeMaterials import CathodeMaterial, ConductiveAdditive, Binder
from OpenCell.Formulations.ElectrodeFormulations import CathodeFormulation, AnodeFormulation

cathode_active_material1 = CathodeMaterial.from_database("NaNiMn P2-O3 Composite")
cathode_active_material1.irreversible_capacity_scaling = 1
cathode_active_material1.reversible_capacity_scaling = 1


cathode_conductive_additive1 = ConductiveAdditive.from_database("Super P")
cathode_conductive_additive2 = ConductiveAdditive.from_database("Graphite")

cathode_binder1 = Binder.from_database("PVDF")
cathode_binder2 = Binder.from_database("CMC")


cathode_formulation = CathodeFormulation(
    active_materials={cathode_active_material1: 90},
    binders={cathode_binder1: 3, cathode_binder2: 2},
    conductive_additives={cathode_conductive_additive1: 3, cathode_conductive_additive2: 2}
)



from OpenCell.Constructions.Electrodes import Cathode
from OpenCell.Materials.RawMaterials import InsulationMaterial


insulation_material = InsulationMaterial.from_database("Aluminium Oxide, 95%")

my_cathode = Cathode(
    formulation=cathode_formulation,
    current_collector=cathode_current_collector,
    calender_density=3,
    mass_loading=15,
    insulation_material=insulation_material,
    insulation_thickness=3
)

my_cathode.half_cell_curve

     Capacity (Ah)  Voltage (V)  Direction  Areal Capacity (mAh/cm²)
0           0.0000       2.8391     charge                    0.0000
1           0.2301       2.8426     charge                    0.0278
2           0.4811       2.8529     charge                    0.0582
3           0.8577       2.8806     charge                    0.1037
4           1.1714       2.9047     charge                    0.1416
..             ...          ...        ...                       ...
109         1.1505       2.2348  discharge                    0.1391
110         1.0041       2.1658  discharge                    0.1214
111         0.8786       2.1105  discharge                    0.1062
112         0.6903       2.0553  discharge                    0.0835
113         0.4184       2.0035  discharge                    0.0506

[114 rows x 4 columns]

In [31]:
half_cell = my_cathode.half_cell_curve.assign(method = 'modelled').drop(columns=['Capacity (Ah)'])
half_cell

     Voltage (V)  Direction  Areal Capacity (mAh/cm²)    method
0         2.8391     charge                    0.0000  modelled
1         2.8426     charge                    0.0278  modelled
2         2.8529     charge                    0.0582  modelled
3         2.8806     charge                    0.1037  modelled
4         2.9047     charge                    0.1416  modelled
..           ...        ...                       ...       ...
109       2.2348  discharge                    0.1391  modelled
110       2.1658  discharge                    0.1214  modelled
111       2.1105  discharge                    0.1062  modelled
112       2.0553  discharge                    0.0835  modelled
113       2.0035  discharge                    0.0506  modelled

[114 rows x 4 columns]