In [1]:
from steer_core.DataManager import DataManager

from steer_materials.CellMaterials.Base import CurrentCollectorMaterial, InsulationMaterial
from steer_materials.CellMaterials.Electrode import CathodeMaterial, Binder, ConductiveAdditive

from steer_opencell_design.Components.CurrentCollectors import PunchedCurrentCollector
from steer_opencell_design.Formulations.ElectrodeFormulations import CathodeFormulation
from steer_opencell_design.Components.Electrodes import Cathode

from steer_opencell_design import __version__

import pandas as pd
from datetime import datetime as dt

In [2]:
db = DataManager()

In [3]:
db.remove_data('cells', "name == 'Vendor D NFPP'")

In [4]:
db.get_data('cells')

,name,object,form_factor,internal_construction,date,version,reference
0,Vendor E NFPP,gASVjoAAAAAAAACMK3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,Prismatic,Stacked,2025-08-11 11:25:32,0.3.5,Na/Na+
1,CBAK-32140NS,gASV5gIAAAAAAACMK3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,Cylindrical,Wound,2025-08-11 11:27:33,0.3.5,Na/Na+
2,Cell 2,gASVjuEAAAAAAACMK3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,Cylindrical,Wound,2025-08-11 11:27:34,0.3.5,Na/Na+
3,Cell 4,gASV/IAAAAAAAACMK3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,Cylindrical,Wound,2025-08-11 11:27:36,0.3.5,Na/Na+
4,HiNa-NaCR32140-MP10,gASV7QIAAAAAAACMK3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,Cylindrical,Wound,2025-08-11 11:27:38,0.3.5,Na/Na+
5,QNAS-S40160NL,gASV5wIAAAAAAACMK3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,Cylindrical,Wound,2025-08-11 11:27:40,0.3.5,Na/Na+
6,QNAS-S40160RL,gASV5wIAAAAAAACMK3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,Cylindrical,Wound,2025-08-11 11:27:42,0.3.5,Na/Na+
7,UniGrid-NCO32140,gASVPWQAAAAAAACMK3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,Cylindrical,Wound,2025-08-11 11:27:43,0.3.5,Na/Na+

In [5]:
db.get_table_names()

['cells',
 'anode_materials',
 'binder_materials',
 'cathode_materials',
 'conductive_additive_materials',
 'current_collector_materials',
 'insulation_materials',
 'separator_materials']

In [6]:
# Get current collector materials from the database

cathode_current_collector_material = CurrentCollectorMaterial.from_database('Aluminum')

In [7]:
# Create the current collector object

cathode_current_collector = PunchedCurrentCollector(
    material=cathode_current_collector_material,
    width=166,
    height=189,
    thickness=13,
    tab_width=50,
    tab_height=20,
    tab_position=50,
    coated_tab_height=4,
    insulation_width=5
)

In [8]:
# Create the cathode formulation

cathode_active_material = CathodeMaterial.from_database("NFPP")
cathode_conductive_additive = ConductiveAdditive.from_database("Super P")
cathode_binder = Binder.from_database("PVDF")


cathode_formulation = CathodeFormulation(
    active_materials={
        cathode_active_material: 95
    },
    binders={
        cathode_binder: 2.5
    },
    conductive_additives={
        cathode_conductive_additive: 2.5
    }
)

cathode_formulation.plot_half_cell_curve(width=600, height=400)

In [9]:
# create the cathode

insulation_material = InsulationMaterial.from_database("Aluminium Oxide, 95%")

my_cathode = Cathode(
    formulation=cathode_formulation,
    current_collector=cathode_current_collector,
    calender_density=1.88,
    mass_loading=18.12,
    insulation_material=insulation_material,
    insulation_thickness=3,
    name='Vendor D NFPP'
)

my_cathode._get_full_top_down_view().show()
my_cathode.plot_half_cell_curve(areal=True, width=600, height=400).show()

In [10]:
my_cathode.properties

{'Mass': '12.45 g',
 'Coating mass': '11.31 g',
 'Total thickness': '205.8 um',
 'Coating thickness': '96.4 um',
 'Porosity': '34.5 %',
 'Cost': '$ 0.16'}

In [11]:

db.insert_data(table_name='cells', data=pd.DataFrame({
    'name': [my_cathode.name],
    'object': [my_cathode.serialize()],
    'form_factor': ['Prismatic'],
    'internal_construction': ['Stacked'],
    'date': [dt.now().strftime("%Y-%m-%d %H:%M:%S")],
    'version': [__version__],
    'reference': ['Na/Na+']
}))

In [12]:
db.get_data(table_name='cells')

,name,object,form_factor,internal_construction,date,version,reference
0,Vendor E NFPP,gASVjoAAAAAAAACMK3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,Prismatic,Stacked,2025-08-11 11:25:32,0.3.5,Na/Na+
1,CBAK-32140NS,gASV5gIAAAAAAACMK3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,Cylindrical,Wound,2025-08-11 11:27:33,0.3.5,Na/Na+
2,Cell 2,gASVjuEAAAAAAACMK3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,Cylindrical,Wound,2025-08-11 11:27:34,0.3.5,Na/Na+
3,Cell 4,gASV/IAAAAAAAACMK3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,Cylindrical,Wound,2025-08-11 11:27:36,0.3.5,Na/Na+
4,HiNa-NaCR32140-MP10,gASV7QIAAAAAAACMK3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,Cylindrical,Wound,2025-08-11 11:27:38,0.3.5,Na/Na+
5,QNAS-S40160NL,gASV5wIAAAAAAACMK3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,Cylindrical,Wound,2025-08-11 11:27:40,0.3.5,Na/Na+
6,QNAS-S40160RL,gASV5wIAAAAAAACMK3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,Cylindrical,Wound,2025-08-11 11:27:42,0.3.5,Na/Na+
7,UniGrid-NCO32140,gASVPWQAAAAAAACMK3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,Cylindrical,Wound,2025-08-11 11:27:43,0.3.5,Na/Na+
8,Vendor D NFPP,gASVjoAAAAAAAACMK3N0ZWVyX29wZW5jZWxsX2Rlc2lnbi...,Prismatic,Stacked,2025-08-11 11:27:45,0.3.5,Na/Na+